/**
 * generate-test-cert.ts
 * สร้าง self-signed X.509 certificate (.p12 / .pfx) สำหรับ dev/test
 * พอได้ cert จริงจาก TDID ให้แทนที่ไฟล์นี้
 *
 * Usage:  npx tsx scripts/generate-test-cert.ts
 * Output: certs/test-company.p12  +  certs/test-company.pem  (public cert)
 */

import forge from 'node-forge';
import fs from 'fs';
import path from 'path';

const CERT_CONFIG = {
  // ─── แก้ข้อมูลบริษัทตรงนี้ ───────────────────────────────────────
  commonName:       'บริษัท สยาม เทคโนโลยี จำกัด',       // ชื่อบริษัท
  organizationName: 'Siam Technology Co Ltd',
  organizationalUnit: 'e-Tax',
  countryName:      'TH',
  stateOrProvince:  'Bangkok',
  localityName:     'Bangkok',
  taxId:            '0105560123456',                     // เลขผู้เสียภาษี
  // ─── Certificate settings ────────────────────────────────────────
  keySize:          2048,
  validYears:       3,
  password:         'etax-dev-password',                  // รหัสผ่าน .p12
};

async function generateCert() {
  console.log('🔐 Generating self-signed e-Tax certificate...\n');

  // 1. Generate RSA key pair
  console.log('  ① Generating 2048-bit RSA key pair...');
  const keys = forge.pki.rsa.generateKeyPair({ bits: CERT_CONFIG.keySize, e: 0x10001 });

  // 2. Create X.509 certificate
  console.log('  ② Creating X.509 certificate...');
  const cert = forge.pki.createCertificate();
  cert.publicKey = keys.publicKey;
  cert.serialNumber = Date.now().toString(16).toUpperCase().padStart(16, '0');

  const now = new Date();
  const expiry = new Date(now);
  expiry.setFullYear(expiry.getFullYear() + CERT_CONFIG.validYears);
  cert.validity.notBefore = now;
  cert.validity.notAfter = expiry;

  // Subject (ข้อมูลบริษัทเรา)
  const attrs = [
    { name: 'commonName',             value: CERT_CONFIG.commonName },
    { name: 'organizationName',       value: CERT_CONFIG.organizationName },
    { name: 'organizationalUnitName', value: CERT_CONFIG.organizationalUnit },
    { name: 'countryName',            value: CERT_CONFIG.countryName },
    { name: 'stateOrProvinceName',    value: CERT_CONFIG.stateOrProvince },
    { name: 'localityName',           value: CERT_CONFIG.localityName },
    // Tax ID ฝังเป็น serialNumber attribute (ETDA standard)
    { name: 'serialNumber',           value: CERT_CONFIG.taxId },
  ];
  cert.setSubject(attrs);
  cert.setIssuer(attrs); // Self-signed → issuer = subject

  // Extensions
  cert.setExtensions([
    { name: 'basicConstraints', cA: false },
    { name: 'keyUsage', digitalSignature: true, nonRepudiation: true, keyEncipherment: false },
    { name: 'extKeyUsage', emailProtection: true, codeSigning: false },
    {
      name: 'subjectAltName',
      altNames: [{ type: 1, value: `taxid:${CERT_CONFIG.taxId}@th` }],
    },
    { name: 'subjectKeyIdentifier' },
  ]);

  // 3. Self-sign with SHA-256
  console.log('  ③ Signing with SHA-256...');
  cert.sign(keys.privateKey, forge.md.sha256.create());

  // 4. Export .p12 (PKCS#12)
  console.log('  ④ Exporting PKCS#12 (.p12)...');
  // node-forge has a known bug where the HMAC-SHA1 outer MAC on PKCS#12
  // computes from a different password encoding than what pkcs12FromAsn1()
  // expects on re-load — resulting in "MAC could not be verified" even
  // with the correct password. For DEV self-signed certs we disable MAC
  // (the content is still AES-256 encrypted via PBE). Real TDID/INET
  // production certs will have valid MACs generated by their HSMs, so
  // the loader must still try WITH-MAC first and fall back gracefully.
  const p12Asn1 = forge.pkcs12.toPkcs12Asn1(
    keys.privateKey,
    [cert],
    CERT_CONFIG.password,
    {
      algorithm: 'aes256',
      friendlyName: CERT_CONFIG.organizationName,
      useMac: false, // dev workaround for forge MAC encoding bug
    },
  );
  const p12Der = forge.asn1.toDer(p12Asn1).getBytes();
  const p12Buffer = Buffer.from(p12Der, 'binary');

  // 5. Export PEM (public cert — ใช้ verify / share กับ RD)
  const certPem = forge.pki.certificateToPem(cert);
  const keyPem  = forge.pki.privateKeyToPem(keys.privateKey);

  // 6. Save files
  const certsDir = path.join(__dirname, '../certs');
  fs.mkdirSync(certsDir, { recursive: true });

  const p12Path  = path.join(certsDir, 'test-company.p12');
  const certPath = path.join(certsDir, 'test-company.pem');
  const keyPath  = path.join(certsDir, 'test-company-key.pem');   // ⚠️ ไม่ commit!
  const infoPath = path.join(certsDir, 'test-company-info.json');

  fs.writeFileSync(p12Path,  p12Buffer);
  fs.writeFileSync(certPath, certPem);
  fs.writeFileSync(keyPath,  keyPem);
  fs.writeFileSync(infoPath, JSON.stringify({
    type: 'SELF_SIGNED_DEV',
    commonName:    CERT_CONFIG.commonName,
    taxId:         CERT_CONFIG.taxId,
    serialNumber:  cert.serialNumber,
    notBefore:     now.toISOString(),
    notAfter:      expiry.toISOString(),
    password:      CERT_CONFIG.password,
    fingerprint:   forge.md.sha256.create()
      .update(forge.asn1.toDer(forge.pki.certificateToAsn1(cert)).getBytes())
      .digest().toHex().toUpperCase().match(/.{2}/g)!.join(':'),
    note: 'DEV ONLY — replace with real TDID cert for production',
  }, null, 2));

  console.log('\n✅ Certificate generated successfully!\n');
  console.log(`  📁 .p12 file  : ${p12Path}`);
  console.log(`  📁 .pem cert  : ${certPath}`);
  console.log(`  📁 info.json  : ${infoPath}`);
  console.log(`\n  🔑 Password   : ${CERT_CONFIG.password}`);
  console.log(`  📅 Valid until: ${expiry.toDateString()}`);
  console.log(`  🔢 Serial     : ${cert.serialNumber}`);
  console.log('\n  ⚠️  ไฟล์ test-company-key.pem มี private key — อย่า commit!\n');

  // 7. Print env vars to set
  console.log('─'.repeat(60));
  console.log('📋 Add to backend/.env:');
  console.log('─'.repeat(60));
  console.log(`CERT_PATH=./certs/test-company.p12`);
  console.log(`CERT_PASSWORD=${CERT_CONFIG.password}`);
  console.log(`RD_ENVIRONMENT=sandbox`);
  console.log('─'.repeat(60));
}

generateCert().catch(console.error);
