import type { InvoiceType } from '../types';

export interface BuiltinDocumentTemplate {
  id: string;
  nameTh: string;
  nameEn: string;
  descriptionTh: string;
  descriptionEn: string;
  tagTh: string;
  tagEn: string;
  accentClass: string;
  /** Tailwind bg colors for color swatch preview [header, accent, body] */
  swatches: [string, string, string];
  supports: InvoiceType[];
}

const ALL_DOCUMENT_TYPES: InvoiceType[] = [
  'tax_invoice',
  'tax_invoice_receipt',
  'receipt',
  'credit_note',
  'debit_note',
];

const rawBuiltinDocumentTemplates: BuiltinDocumentTemplate[] = [
  {
    id: 'builtin:simple-slate',
    nameTh: 'เรียบง่าย — เทาเข้ม',
    nameEn: 'Simple Slate',
    descriptionTh: 'สะอาด อ่านง่าย ใช้ได้กับลูกค้าทุกกลุ่ม โทนเทาเข้มแบบมืออาชีพ',
    descriptionEn: 'Clean, readable, and professional in a calm slate tone.',
    tagTh: 'เทาเข้ม',
    tagEn: 'Slate',
    accentClass: 'border-slate-200 bg-slate-50 text-slate-700',
    swatches: ['bg-slate-700', 'bg-slate-400', 'bg-slate-100'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:official-navy',
    nameTh: 'ทางการ — น้ำเงินกรมท่า',
    nameEn: 'Official Navy',
    descriptionTh: 'โทนน้ำเงินกรมท่า เหมาะกับเอกสารบริษัท งานราชการ และเอกสารที่ต้องดูน่าเชื่อถือ',
    descriptionEn: 'Formal navy styling for corporate, government, and high-trust documents.',
    tagTh: 'น้ำเงินกรมท่า',
    tagEn: 'Navy',
    accentClass: 'border-blue-200 bg-blue-50 text-blue-700',
    swatches: ['bg-blue-900', 'bg-blue-500', 'bg-blue-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:luxury-gold',
    nameTh: 'หรูหรา — ดำทอง',
    nameEn: 'Luxury Gold',
    descriptionTh: 'โทนดำทอง พรีเมียม เหมาะกับแบรนด์ที่อยากให้เอกสารดูแพงและมีระดับ',
    descriptionEn: 'A premium black-and-gold tone for elevated brand documents.',
    tagTh: 'ดำทอง',
    tagEn: 'Gold',
    accentClass: 'border-yellow-300 bg-yellow-50 text-yellow-800',
    swatches: ['bg-neutral-900', 'bg-yellow-400', 'bg-yellow-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:local-friendly',
    nameTh: 'อบอุ่น — เป็นกันเอง',
    nameEn: 'Local Friendly',
    descriptionTh: 'โทนอบอุ่น ตัวเอกสารดูเป็นมิตร อ่านง่าย เหมาะกับร้านค้าและธุรกิจทั่วไป',
    descriptionEn: 'Warm, approachable, and easy to read for everyday businesses.',
    tagTh: 'อบอุ่น',
    tagEn: 'Warm',
    accentClass: 'border-orange-200 bg-orange-50 text-orange-700',
    swatches: ['bg-orange-600', 'bg-amber-400', 'bg-orange-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:accounting-green',
    nameTh: 'บัญชี — เขียวสุภาพ',
    nameEn: 'Accounting Green',
    descriptionTh: 'โทนเขียว สุภาพ เหมาะกับใบเสร็จ งานรับชำระ และเอกสารที่เน้นความเรียบร้อย',
    descriptionEn: 'A tidy green tone for receipts, payment records, and accounting workflows.',
    tagTh: 'เขียว',
    tagEn: 'Green',
    accentClass: 'border-emerald-200 bg-emerald-50 text-emerald-700',
    swatches: ['bg-emerald-700', 'bg-emerald-400', 'bg-emerald-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:soft-cyan',
    nameTh: 'ทันสมัย — ฟ้าเขียว',
    nameEn: 'Modern Cyan',
    descriptionTh: 'โทนฟ้าอมเขียว ดูทันสมัย เหมาะกับบริษัทเทคโนโลยีและบริการดิจิทัล',
    descriptionEn: 'A modern cyan tone for technology and digital-service companies.',
    tagTh: 'ฟ้าเขียว',
    tagEn: 'Cyan',
    accentClass: 'border-cyan-200 bg-cyan-50 text-cyan-700',
    swatches: ['bg-cyan-700', 'bg-cyan-400', 'bg-cyan-100'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-white',
    nameTh: '01 Minimal White',
    nameEn: '01 Minimal White',
    descriptionTh: 'ขาวสะอาดแบบ marketplace พร้อมโครงเอกสารครบ',
    descriptionEn: 'Clean white marketplace preview with complete document structure',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-gray-200',
    swatches: ['bg-white', 'bg-gray-200', 'bg-gray-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-light-gray',
    nameTh: '06 Soft Gray',
    nameEn: '06 Soft Gray',
    descriptionTh: 'เทาอ่อนนุ่ม ดูเป็นมืออาชีพ',
    descriptionEn: 'Soft gray, clean and professional',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-gray-400',
    swatches: ['bg-gray-100', 'bg-gray-400', 'bg-gray-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-line',
    nameTh: '12 Minimal Line',
    nameEn: '12 Minimal Line',
    descriptionTh: 'เส้นบาง คม เรียบหรู',
    descriptionEn: 'Thin rules, crisp and refined',
    tagTh: 'เรียบ-สด',
    tagEn: 'Minimal',
    accentClass: 'bg-teal-500',
    swatches: ['bg-white', 'bg-teal-500', 'bg-teal-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-mint',
    nameTh: '13 Minimal Mint',
    nameEn: '13 Minimal Mint',
    descriptionTh: 'มิ้นท์นุ่ม สะอาด เหมาะกับบริการสุขภาพ/ร้านค้า',
    descriptionEn: 'Soft mint, clean and fresh',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-emerald-200',
    swatches: ['bg-emerald-50', 'bg-emerald-400', 'bg-emerald-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-beige',
    nameTh: '14 Minimal Beige',
    nameEn: '14 Minimal Beige',
    descriptionTh: 'เบจอุ่น เรียบแพง อ่านง่าย',
    descriptionEn: 'Warm beige, quiet and elevated',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-amber-200',
    swatches: ['bg-orange-50', 'bg-amber-400', 'bg-yellow-800'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-dark-accent',
    nameTh: '15 Minimal Dark Accent',
    nameEn: '15 Minimal Dark Accent',
    descriptionTh: 'Minimal ขาวดำพร้อม accent เข้ม',
    descriptionEn: 'Minimal white document with strong dark accents',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-gray-900',
    swatches: ['bg-white', 'bg-gray-900', 'bg-gray-200'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-pink',
    nameTh: '10 Anime Friendly',
    nameEn: '10 Anime Friendly',
    descriptionTh: 'ชมพูอนิเมะเป็นมิตร มีพื้นที่ QR และยอดรวมชัดเจน',
    descriptionEn: 'Friendly anime pink with clear QR and total sections',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-pink-100',
    swatches: ['bg-pink-200', 'bg-pink-400', 'bg-pink-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-blue',
    nameTh: '17 Cute Baby Blue',
    nameEn: '17 Cute Baby Blue',
    descriptionTh: 'ฟ้าอ่อน หมีน้อย',
    descriptionEn: 'Soft blue with bear mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-blue-100',
    swatches: ['bg-blue-200', 'bg-blue-400', 'bg-blue-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-yellow',
    nameTh: '19 Cute Yellow Sunshine',
    nameEn: '19 Cute Yellow Sunshine',
    descriptionTh: 'เหลืองสดใส ดวงอาทิตย์',
    descriptionEn: 'Sunny yellow with sun mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-yellow-100',
    swatches: ['bg-yellow-200', 'bg-yellow-400', 'bg-amber-500'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-green',
    nameTh: '18 Cute Soft Green',
    nameEn: '18 Cute Soft Green',
    descriptionTh: 'เขียวสด ไดโนน้อย',
    descriptionEn: 'Fresh green with dino mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-emerald-100',
    swatches: ['bg-emerald-200', 'bg-emerald-400', 'bg-emerald-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-kawaii',
    nameTh: '20 Cute Lovely Purple',
    nameEn: '20 Cute Lovely Purple',
    descriptionTh: 'ม่วงคาวาอี้ แมวน้อย',
    descriptionEn: 'Purple kawaii with cat mascot',
    tagTh: 'คาวาอี้',
    tagEn: 'Kawaii',
    accentClass: 'bg-violet-100',
    swatches: ['bg-violet-200', 'bg-violet-400', 'bg-violet-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-blue-modern',
    nameTh: '02 Corporate Blue',
    nameEn: '02 Corporate Blue',
    descriptionTh: 'น้ำเงินองค์กร โครงหัวเอกสารหนักแน่น',
    descriptionEn: 'Corporate blue with a strong header system.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-blue-800',
    swatches: ['bg-blue-800', 'bg-blue-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-bw',
    nameTh: 'Pro ขาวดำ',
    nameEn: 'Pro Black & White',
    descriptionTh: 'ขาวดำคลาสสิก ดูน่าเชื่อถือ',
    descriptionEn: 'Classic black and white, high-trust corporate.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-gray-900',
    swatches: ['bg-gray-900', 'bg-gray-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-navy',
    nameTh: '07 Thai Official',
    nameEn: '07 Thai Official',
    descriptionTh: 'ลายไทยทางการ น้ำเงินสุภาพ',
    descriptionEn: 'Formal Thai official style in refined navy.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-blue-950',
    swatches: ['bg-blue-950', 'bg-blue-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-soft-pastel',
    nameTh: 'Pro พาสเทล',
    nameEn: 'Pro Soft Pastel',
    descriptionTh: 'ม่วงพาสเทล นุ่มนวล แต่ดูมืออาชีพ',
    descriptionEn: 'Soft violet pastel, gentle yet professional.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-violet-200',
    swatches: ['bg-violet-200', 'bg-violet-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-corp-teal',
    nameTh: 'Pro เขียวน้ำ',
    nameEn: 'Pro Corporate Teal',
    descriptionTh: 'เขียวน้ำ สดชื่น เหมาะกับบริษัทเทคโนโลยี',
    descriptionEn: 'Teal corporate style for tech and services.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-teal-700',
    swatches: ['bg-teal-700', 'bg-teal-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-elegant-beige',
    nameTh: 'Pro เบจ',
    nameEn: 'Pro Elegant Beige',
    descriptionTh: 'โทนเบจทอง หรูหราและดูมีระดับ',
    descriptionEn: 'Warm beige and gold, elegant and premium.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-amber-200',
    swatches: ['bg-amber-200', 'bg-amber-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-green-eco',
    nameTh: '03 Green e-Tax',
    nameEn: '03 Green e-Tax',
    descriptionTh: 'เขียว e-Tax สดชื่น พร้อมพื้นที่ตรวจสอบเอกสาร',
    descriptionEn: 'Fresh green e-Tax styling with verification area.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-green-800',
    swatches: ['bg-green-800', 'bg-green-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-gradient',
    nameTh: '08 Modern Gradient',
    nameEn: '08 Modern Gradient',
    descriptionTh: 'Gradient ทันสมัย สีสดแบบ template marketplace',
    descriptionEn: 'Modern vivid gradient for marketplace-style previews.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-violet-500',
    swatches: ['bg-blue-700', 'bg-violet-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-classic-orange',
    nameTh: '09 Logistics Orange',
    nameEn: '09 Logistics Orange',
    descriptionTh: 'ส้มโลจิสติกส์ สด ชัด เหมาะกับงานขนส่ง',
    descriptionEn: 'Clear logistics orange for transport and service businesses.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-orange-200',
    swatches: ['bg-orange-200', 'bg-orange-600', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:crayon',
    nameTh: 'Crayon Drawing',
    nameEn: 'Crayon Drawing 🖍️',
    descriptionTh: 'สไตล์วาดด้วยมือ เหมือนเด็กวาด สีสันสดใสสนุกสนาน',
    descriptionEn: 'Hand-drawn childlike style with playful crayon colors.',
    tagTh: 'สนุก',
    tagEn: 'Fun',
    accentClass: 'bg-red-400',
    swatches: ['bg-red-400', 'bg-yellow-300', 'bg-blue-400'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-biz-clean',
    nameTh: 'Pro สะอาด',
    nameEn: 'Pro Biz Clean',
    descriptionTh: 'เทาอ่อน สะอาด เป็นระเบียบ เหมาะกับทุกธุรกิจ',
    descriptionEn: 'Light slate, clean and orderly for any business.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-slate-200',
    swatches: ['bg-slate-200', 'bg-slate-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  // ── Dark / Man / Tech ──────────────────────────────────────────
  { id: 'builtin:dark-king',     nameTh: 'Dark King',       nameEn: 'Dark King',       descriptionTh: 'พื้นดำ ทอง หรูหราทรงพลัง',              descriptionEn: 'Black & gold, powerful and luxurious',        tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-yellow-500', swatches: ['bg-neutral-950', 'bg-yellow-500', 'bg-neutral-900'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-samurai',  nameTh: 'Steel Samurai',   nameEn: 'Steel Samurai',   descriptionTh: 'พื้นดำ แดง สไตล์นักรบ',                 descriptionEn: 'Dark warrior style with crimson accent',       tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-red-700',    swatches: ['bg-neutral-950', 'bg-red-700',    'bg-neutral-800'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-carbon',   nameTh: '05 Dark Tech',     nameEn: '05 Dark Tech',     descriptionTh: 'พื้นดำ Cyan เทคโนโลยีสูง',              descriptionEn: 'Carbon black with electric cyan',              tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-cyan-500',   swatches: ['bg-neutral-950', 'bg-cyan-500',   'bg-cyan-950'],    supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-wolf',     nameTh: 'Midnight Wolf',   nameEn: 'Midnight Wolf',   descriptionTh: 'น้ำเงินเข้ม มืดลึก สง่างาม',            descriptionEn: 'Deep midnight blue, mysterious and elegant',   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-blue-400',   swatches: ['bg-slate-950',   'bg-blue-400',   'bg-slate-900'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-shadow',   nameTh: 'Shadow Tech',     nameEn: 'Shadow Tech',     descriptionTh: 'ม่วงเข้ม เทค มืดลึก',                   descriptionEn: 'Dark purple tech aesthetic',                   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-purple-600', swatches: ['bg-neutral-950', 'bg-purple-600', 'bg-purple-950'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-matrix',   nameTh: 'Black Matrix',    nameEn: 'Black Matrix',    descriptionTh: 'Matrix สีเขียว Hacker',                  descriptionEn: 'Matrix-style green on black',                  tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-green-400',  swatches: ['bg-neutral-950', 'bg-green-400',  'bg-green-950'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-graffiti', nameTh: 'Urban Graffiti',  nameEn: 'Urban Graffiti',  descriptionTh: 'ดำ ส้มสด Urban Street',                  descriptionEn: 'Urban street style, black and vivid orange',   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-orange-500', swatches: ['bg-neutral-900', 'bg-orange-500', 'bg-neutral-800'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-cyber',    nameTh: 'Cyber Neon',      nameEn: 'Cyber Neon',      descriptionTh: 'Cyberpunk Neon สีฟ้าเรือง',              descriptionEn: 'Cyberpunk neon cyan on deep space',            tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-cyan-400',   swatches: ['bg-violet-950', 'bg-cyan-400',   'bg-violet-900'],  supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-gold',     nameTh: '04 Luxury Gold',  nameEn: '04 Luxury Gold',  descriptionTh: 'พื้นดำ ทองบริสุทธิ์ Luxury',            descriptionEn: 'Pure black with pure gold luxury',             tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-yellow-400', swatches: ['bg-stone-950',   'bg-yellow-400', 'bg-stone-900'],  supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-mono',     nameTh: 'Mono Minimal',    nameEn: 'Mono Minimal',    descriptionTh: 'ขาวดำ Minimal หมดจด',                   descriptionEn: 'Pure monochrome minimalism',                   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-white',      swatches: ['bg-neutral-950', 'bg-white',       'bg-neutral-800'], supports: ALL_DOCUMENT_TYPES },
  // ── Anime / Otaku ──────────────────────────────────────────────
  { id: 'builtin:anime-ink',     nameTh: 'Anime Black Ink',    nameEn: 'Anime Black Ink',    descriptionTh: 'สไตล์มังงะ ขาวดำ หมึก',                  descriptionEn: 'Manga-style black ink on white',               tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-red-600',    swatches: ['bg-neutral-900', 'bg-red-600',    'bg-white'],       supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-flame',   nameTh: 'Anime Red Flame',    nameEn: 'Anime Red Flame',    descriptionTh: 'เปลวไฟแดง พลังนักสู้',                   descriptionEn: 'Fierce red flame energy',                      tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-red-500',    swatches: ['bg-red-700',     'bg-red-400',    'bg-red-50'],      supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-energy',  nameTh: 'Anime Blue Energy',  nameEn: 'Anime Blue Energy',  descriptionTh: 'พลังน้ำเงิน สายฟ้า',                     descriptionEn: 'Electric blue energy burst',                   tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-blue-500',   swatches: ['bg-blue-700',    'bg-blue-400',   'bg-blue-50'],     supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-shadow',  nameTh: 'Anime Purple Shadow', nameEn: 'Anime Purple Shadow', descriptionTh: 'เงาม่วง พลังมืด',                       descriptionEn: 'Dark purple shadow power',                     tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-purple-500', swatches: ['bg-purple-700',  'bg-purple-400', 'bg-purple-50'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-mecha',   nameTh: 'Anime Mecha Gear',   nameEn: 'Anime Mecha Gear',   descriptionTh: 'หุ่นยนต์กล Mecha สีเทา',                descriptionEn: 'Mecha steel gray robotic',                     tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-slate-500',  swatches: ['bg-slate-800',   'bg-slate-400',  'bg-slate-100'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-chibi',   nameTh: 'Anime Chibi Cute',   nameEn: 'Anime Chibi Cute',   descriptionTh: 'จิบิน่ารัก ชมพู ดาว',                   descriptionEn: 'Chibi-cute pink with sparkles',                tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-pink-500',   swatches: ['bg-pink-500',    'bg-pink-300',   'bg-pink-50'],     supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-idol',    nameTh: 'Anime Idol Stage',   nameEn: 'Anime Idol Stage',   descriptionTh: 'Idol เวที ทอง แสงสว่าง',                 descriptionEn: 'Idol stage gold and spotlight',                tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-yellow-500', swatches: ['bg-yellow-600',  'bg-yellow-300', 'bg-yellow-50'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-fantasy', nameTh: 'Anime Fantasy',      nameEn: 'Anime Fantasy',      descriptionTh: 'แฟนตาซี เขียวมรกต ป่าวิเศษ',            descriptionEn: 'Mystical forest green fantasy',                tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-emerald-600',swatches: ['bg-emerald-700', 'bg-emerald-400','bg-emerald-50'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-tokyo',   nameTh: 'Anime Tokyo Night',  nameEn: 'Anime Tokyo Night',  descriptionTh: 'Tokyo ยามค่ำ Neon แดง',                  descriptionEn: 'Tokyo night neon red cityscape',               tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-red-500',    swatches: ['bg-indigo-950',  'bg-red-500',    'bg-indigo-900'],  supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-pastel',  nameTh: 'Anime Pastel Otaku', nameEn: 'Anime Pastel Otaku', descriptionTh: 'Otaku พาสเทล ม่วงอ่อน',                  descriptionEn: 'Otaku soft pastel violet',                     tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-violet-400', swatches: ['bg-violet-200',  'bg-violet-400', 'bg-violet-50'],   supports: ALL_DOCUMENT_TYPES },
];

const HIDDEN_LEGACY_TEMPLATES = new Set([
  'builtin:simple-slate',
  'builtin:official-navy',
  'builtin:luxury-gold',
  'builtin:local-friendly',
  'builtin:accounting-green',
  'builtin:soft-cyan',
  'builtin:minimal-gray',
  'builtin:minimal-sans',
  'builtin:minimal-space',
  'builtin:pro-bw',
  'builtin:pro-soft-pastel',
  'builtin:pro-corp-teal',
  'builtin:pro-elegant-beige',
  'builtin:pro-biz-clean',
  'builtin:crayon',
  'builtin:anime-ink',
  'builtin:anime-flame',
  'builtin:anime-energy',
  'builtin:anime-shadow',
  'builtin:anime-mecha',
  'builtin:anime-chibi',
  'builtin:anime-idol',
  'builtin:anime-fantasy',
  'builtin:anime-tokyo',
  'builtin:anime-pastel',
]);

const TEMPLATE_GROUP_ORDER: Record<string, number> = {
  Dark: 10,
  Minimal: 20,
  Cute: 30,
  Kawaii: 31,
};

const TEMPLATE_CATALOG_ORDER = new Map([
  'builtin:dark-king',
  'builtin:dark-samurai',
  'builtin:dark-carbon',
  'builtin:dark-wolf',
  'builtin:dark-shadow',
  'builtin:dark-matrix',
  'builtin:dark-graffiti',
  'builtin:dark-cyber',
  'builtin:dark-gold',
  'builtin:dark-mono',
  'builtin:minimal-light-gray',
  'builtin:minimal-line',
  'builtin:minimal-mint',
  'builtin:minimal-beige',
  'builtin:minimal-dark-accent',
  'builtin:cute-pink',
  'builtin:cute-blue',
  'builtin:cute-green',
  'builtin:cute-yellow',
  'builtin:cute-kawaii',
].map((id, index) => [id, index]));

export const builtinDocumentTemplates: BuiltinDocumentTemplate[] = rawBuiltinDocumentTemplates
  .filter((template) => !HIDDEN_LEGACY_TEMPLATES.has(template.id))
  .sort((a, b) => {
    const catalogA = TEMPLATE_CATALOG_ORDER.get(a.id) ?? 9999;
    const catalogB = TEMPLATE_CATALOG_ORDER.get(b.id) ?? 9999;
    if (catalogA !== catalogB) return catalogA - catalogB;
    const groupA = TEMPLATE_GROUP_ORDER[a.tagEn] ?? 999;
    const groupB = TEMPLATE_GROUP_ORDER[b.tagEn] ?? 999;
    if (groupA !== groupB) return groupA - groupB;
    return a.nameEn.localeCompare(b.nameEn);
  });

export function supportsDocumentType(template: BuiltinDocumentTemplate, type: InvoiceType) {
  return template.supports.includes(type);
}
