import type { InvoiceType } from '../types';

export interface BuiltinDocumentTemplate {
  id: string;
  nameTh: string;
  nameEn: string;
  descriptionTh: string;
  descriptionEn: string;
  tagTh: string;
  tagEn: string;
  accentClass: string;
  /** Tailwind bg colors for color swatch preview [header, accent, body] */
  swatches: [string, string, string];
  supports: InvoiceType[];
}

const ALL_DOCUMENT_TYPES: InvoiceType[] = [
  'tax_invoice',
  'tax_invoice_receipt',
  'receipt',
  'credit_note',
  'debit_note',
];

export const builtinDocumentTemplates: BuiltinDocumentTemplate[] = [
  {
    id: 'builtin:simple-slate',
    nameTh: 'เรียบง่าย — เทาเข้ม',
    nameEn: 'Simple Slate',
    descriptionTh: 'สะอาด อ่านง่าย ใช้ได้กับลูกค้าทุกกลุ่ม โทนเทาเข้มแบบมืออาชีพ',
    descriptionEn: 'Clean, readable, and professional in a calm slate tone.',
    tagTh: 'เทาเข้ม',
    tagEn: 'Slate',
    accentClass: 'border-slate-200 bg-slate-50 text-slate-700',
    swatches: ['bg-slate-700', 'bg-slate-400', 'bg-slate-100'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:official-navy',
    nameTh: 'ทางการ — น้ำเงินกรมท่า',
    nameEn: 'Official Navy',
    descriptionTh: 'โทนน้ำเงินกรมท่า เหมาะกับเอกสารบริษัท งานราชการ และเอกสารที่ต้องดูน่าเชื่อถือ',
    descriptionEn: 'Formal navy styling for corporate, government, and high-trust documents.',
    tagTh: 'น้ำเงินกรมท่า',
    tagEn: 'Navy',
    accentClass: 'border-blue-200 bg-blue-50 text-blue-700',
    swatches: ['bg-blue-900', 'bg-blue-500', 'bg-blue-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:luxury-gold',
    nameTh: 'หรูหรา — ดำทอง',
    nameEn: 'Luxury Gold',
    descriptionTh: 'โทนดำทอง พรีเมียม เหมาะกับแบรนด์ที่อยากให้เอกสารดูแพงและมีระดับ',
    descriptionEn: 'A premium black-and-gold tone for elevated brand documents.',
    tagTh: 'ดำทอง',
    tagEn: 'Gold',
    accentClass: 'border-yellow-300 bg-yellow-50 text-yellow-800',
    swatches: ['bg-neutral-900', 'bg-yellow-400', 'bg-yellow-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:local-friendly',
    nameTh: 'อบอุ่น — เป็นกันเอง',
    nameEn: 'Local Friendly',
    descriptionTh: 'โทนอบอุ่น ตัวเอกสารดูเป็นมิตร อ่านง่าย เหมาะกับร้านค้าและธุรกิจทั่วไป',
    descriptionEn: 'Warm, approachable, and easy to read for everyday businesses.',
    tagTh: 'อบอุ่น',
    tagEn: 'Warm',
    accentClass: 'border-orange-200 bg-orange-50 text-orange-700',
    swatches: ['bg-orange-600', 'bg-amber-400', 'bg-orange-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:accounting-green',
    nameTh: 'บัญชี — เขียวสุภาพ',
    nameEn: 'Accounting Green',
    descriptionTh: 'โทนเขียว สุภาพ เหมาะกับใบเสร็จ งานรับชำระ และเอกสารที่เน้นความเรียบร้อย',
    descriptionEn: 'A tidy green tone for receipts, payment records, and accounting workflows.',
    tagTh: 'เขียว',
    tagEn: 'Green',
    accentClass: 'border-emerald-200 bg-emerald-50 text-emerald-700',
    swatches: ['bg-emerald-700', 'bg-emerald-400', 'bg-emerald-50'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:soft-cyan',
    nameTh: 'ทันสมัย — ฟ้าเขียว',
    nameEn: 'Modern Cyan',
    descriptionTh: 'โทนฟ้าอมเขียว ดูทันสมัย เหมาะกับบริษัทเทคโนโลยีและบริการดิจิทัล',
    descriptionEn: 'A modern cyan tone for technology and digital-service companies.',
    tagTh: 'ฟ้าเขียว',
    tagEn: 'Cyan',
    accentClass: 'border-cyan-200 bg-cyan-50 text-cyan-700',
    swatches: ['bg-cyan-700', 'bg-cyan-400', 'bg-cyan-100'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-white',
    nameTh: 'Minimal White',
    nameEn: 'Minimal White',
    descriptionTh: 'สะอาด ขาว ไม่มีตกแต่ง',
    descriptionEn: 'Clean white, no decorations',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-gray-200',
    swatches: ['bg-white', 'bg-gray-200', 'bg-gray-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-gray',
    nameTh: 'Minimal Gray',
    nameEn: 'Minimal Gray',
    descriptionTh: 'เทาอ่อน สบายตา',
    descriptionEn: 'Soft gray, easy on the eyes',
    tagTh: 'เรียบง่าย',
    tagEn: 'Minimal',
    accentClass: 'bg-gray-400',
    swatches: ['bg-gray-100', 'bg-gray-400', 'bg-gray-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-line',
    nameTh: 'Minimal Line',
    nameEn: 'Minimal Line',
    descriptionTh: 'เส้นเขียว สดใส สะอาด',
    descriptionEn: 'Teal accent line, clean layout',
    tagTh: 'เรียบ-สด',
    tagEn: 'Clean',
    accentClass: 'bg-teal-500',
    swatches: ['bg-white', 'bg-teal-500', 'bg-teal-700'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-sans',
    nameTh: 'Minimal Sans',
    nameEn: 'Minimal Sans',
    descriptionTh: 'ตัวหนา ดำแข็ง ทันสมัย',
    descriptionEn: 'Bold type, strong contrast',
    tagTh: 'ตัวหนา',
    tagEn: 'Bold',
    accentClass: 'bg-gray-900',
    swatches: ['bg-white', 'bg-gray-800', 'bg-gray-900'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:minimal-space',
    nameTh: 'Minimal Space',
    nameEn: 'Minimal Space',
    descriptionTh: 'โปร่งกว้าง ระยะห่างมาก',
    descriptionEn: 'Spacious layout, lots of whitespace',
    tagTh: 'โปร่ง',
    tagEn: 'Spacious',
    accentClass: 'bg-slate-300',
    swatches: ['bg-slate-50', 'bg-slate-300', 'bg-slate-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-pink',
    nameTh: 'Cute Pink',
    nameEn: 'Cute Pink',
    descriptionTh: 'ชมพูน่ารัก กระต่ายน้อย',
    descriptionEn: 'Sweet pink with bunny mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-pink-100',
    swatches: ['bg-pink-200', 'bg-pink-400', 'bg-pink-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-blue',
    nameTh: 'Cute Blue',
    nameEn: 'Cute Blue',
    descriptionTh: 'ฟ้าอ่อน หมีน้อย',
    descriptionEn: 'Soft blue with bear mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-blue-100',
    swatches: ['bg-blue-200', 'bg-blue-400', 'bg-blue-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-yellow',
    nameTh: 'Cute Yellow',
    nameEn: 'Cute Yellow',
    descriptionTh: 'เหลืองสดใส ดวงอาทิตย์',
    descriptionEn: 'Sunny yellow with sun mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-yellow-100',
    swatches: ['bg-yellow-200', 'bg-yellow-400', 'bg-amber-500'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-green',
    nameTh: 'Cute Green',
    nameEn: 'Cute Green',
    descriptionTh: 'เขียวสด ไดโนน้อย',
    descriptionEn: 'Fresh green with dino mascot',
    tagTh: 'คิ้วท์',
    tagEn: 'Cute',
    accentClass: 'bg-emerald-100',
    swatches: ['bg-emerald-200', 'bg-emerald-400', 'bg-emerald-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:cute-kawaii',
    nameTh: 'Cute Kawaii',
    nameEn: 'Cute Kawaii',
    descriptionTh: 'ม่วงคาวาอี้ แมวน้อย',
    descriptionEn: 'Purple kawaii with cat mascot',
    tagTh: 'คาวาอี้',
    tagEn: 'Kawaii',
    accentClass: 'bg-violet-100',
    swatches: ['bg-violet-200', 'bg-violet-400', 'bg-violet-600'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-blue-modern',
    nameTh: 'Pro สีน้ำเงิน',
    nameEn: 'Pro Blue Modern',
    descriptionTh: 'โทนน้ำเงินทันสมัย หัวเข้มมืออาชีพ',
    descriptionEn: 'Modern blue header, clean corporate layout.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-blue-800',
    swatches: ['bg-blue-800', 'bg-blue-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-bw',
    nameTh: 'Pro ขาวดำ',
    nameEn: 'Pro Black & White',
    descriptionTh: 'ขาวดำคลาสสิก ดูน่าเชื่อถือ',
    descriptionEn: 'Classic black and white, high-trust corporate.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-gray-900',
    swatches: ['bg-gray-900', 'bg-gray-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-navy',
    nameTh: 'Pro กรมท่า',
    nameEn: 'Pro Navy',
    descriptionTh: 'น้ำเงินเข้มกรมท่า เหมาะกับองค์กรและราชการ',
    descriptionEn: 'Deep navy for corporate and government documents.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-blue-950',
    swatches: ['bg-blue-950', 'bg-blue-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-soft-pastel',
    nameTh: 'Pro พาสเทล',
    nameEn: 'Pro Soft Pastel',
    descriptionTh: 'ม่วงพาสเทล นุ่มนวล แต่ดูมืออาชีพ',
    descriptionEn: 'Soft violet pastel, gentle yet professional.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-violet-200',
    swatches: ['bg-violet-200', 'bg-violet-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-corp-teal',
    nameTh: 'Pro เขียวน้ำ',
    nameEn: 'Pro Corporate Teal',
    descriptionTh: 'เขียวน้ำ สดชื่น เหมาะกับบริษัทเทคโนโลยี',
    descriptionEn: 'Teal corporate style for tech and services.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-teal-700',
    swatches: ['bg-teal-700', 'bg-teal-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-elegant-beige',
    nameTh: 'Pro เบจ',
    nameEn: 'Pro Elegant Beige',
    descriptionTh: 'โทนเบจทอง หรูหราและดูมีระดับ',
    descriptionEn: 'Warm beige and gold, elegant and premium.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-amber-200',
    swatches: ['bg-amber-200', 'bg-amber-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-green-eco',
    nameTh: 'Pro เขียว Eco',
    nameEn: 'Pro Green Eco',
    descriptionTh: 'เขียวเข้ม Eco สำหรับธุรกิจที่ใส่ใจสิ่งแวดล้อม',
    descriptionEn: 'Deep green eco theme for sustainable businesses.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-green-800',
    swatches: ['bg-green-800', 'bg-green-100', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-gradient',
    nameTh: 'Pro Gradient',
    nameEn: 'Pro Gradient',
    descriptionTh: 'Gradient น้ำเงิน-ม่วง ดูทันสมัยและโดดเด่น',
    descriptionEn: 'Blue-to-violet gradient header, eye-catching and modern.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-violet-500',
    swatches: ['bg-blue-700', 'bg-violet-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-classic-orange',
    nameTh: 'Pro ส้มคลาสสิก',
    nameEn: 'Pro Classic Orange',
    descriptionTh: 'ส้มอบอุ่น สีคลาสสิก เหมาะกับธุรกิจบริการ',
    descriptionEn: 'Warm orange classic tone for service businesses.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-orange-200',
    swatches: ['bg-orange-200', 'bg-orange-600', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:crayon',
    nameTh: 'Crayon Drawing',
    nameEn: 'Crayon Drawing 🖍️',
    descriptionTh: 'สไตล์วาดด้วยมือ เหมือนเด็กวาด สีสันสดใสสนุกสนาน',
    descriptionEn: 'Hand-drawn childlike style with playful crayon colors.',
    tagTh: 'สนุก',
    tagEn: 'Fun',
    accentClass: 'bg-red-400',
    swatches: ['bg-red-400', 'bg-yellow-300', 'bg-blue-400'],
    supports: ALL_DOCUMENT_TYPES,
  },
  {
    id: 'builtin:pro-biz-clean',
    nameTh: 'Pro สะอาด',
    nameEn: 'Pro Biz Clean',
    descriptionTh: 'เทาอ่อน สะอาด เป็นระเบียบ เหมาะกับทุกธุรกิจ',
    descriptionEn: 'Light slate, clean and orderly for any business.',
    tagTh: 'โปร',
    tagEn: 'Pro',
    accentClass: 'bg-slate-200',
    swatches: ['bg-slate-200', 'bg-slate-500', 'bg-white'],
    supports: ALL_DOCUMENT_TYPES,
  },
  // ── Dark / Man / Tech ──────────────────────────────────────────
  { id: 'builtin:dark-king',     nameTh: 'Dark King',       nameEn: 'Dark King',       descriptionTh: 'พื้นดำ ทอง หรูหราทรงพลัง',              descriptionEn: 'Black & gold, powerful and luxurious',        tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-yellow-500', swatches: ['bg-neutral-950', 'bg-yellow-500', 'bg-neutral-900'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-samurai',  nameTh: 'Steel Samurai',   nameEn: 'Steel Samurai',   descriptionTh: 'พื้นดำ แดง สไตล์นักรบ',                 descriptionEn: 'Dark warrior style with crimson accent',       tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-red-700',    swatches: ['bg-neutral-950', 'bg-red-700',    'bg-neutral-800'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-carbon',   nameTh: 'Carbon X',        nameEn: 'Carbon X',        descriptionTh: 'พื้นดำ Cyan เทคโนโลยีสูง',              descriptionEn: 'Carbon black with electric cyan',              tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-cyan-500',   swatches: ['bg-neutral-950', 'bg-cyan-500',   'bg-cyan-950'],    supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-wolf',     nameTh: 'Midnight Wolf',   nameEn: 'Midnight Wolf',   descriptionTh: 'น้ำเงินเข้ม มืดลึก สง่างาม',            descriptionEn: 'Deep midnight blue, mysterious and elegant',   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-blue-400',   swatches: ['bg-slate-950',   'bg-blue-400',   'bg-slate-900'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-shadow',   nameTh: 'Shadow Tech',     nameEn: 'Shadow Tech',     descriptionTh: 'ม่วงเข้ม เทค มืดลึก',                   descriptionEn: 'Dark purple tech aesthetic',                   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-purple-600', swatches: ['bg-neutral-950', 'bg-purple-600', 'bg-purple-950'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-matrix',   nameTh: 'Black Matrix',    nameEn: 'Black Matrix',    descriptionTh: 'Matrix สีเขียว Hacker',                  descriptionEn: 'Matrix-style green on black',                  tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-green-400',  swatches: ['bg-neutral-950', 'bg-green-400',  'bg-green-950'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-graffiti', nameTh: 'Urban Graffiti',  nameEn: 'Urban Graffiti',  descriptionTh: 'ดำ ส้มสด Urban Street',                  descriptionEn: 'Urban street style, black and vivid orange',   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-orange-500', swatches: ['bg-neutral-900', 'bg-orange-500', 'bg-neutral-800'], supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-cyber',    nameTh: 'Cyber Neon',      nameEn: 'Cyber Neon',      descriptionTh: 'Cyberpunk Neon สีฟ้าเรือง',              descriptionEn: 'Cyberpunk neon cyan on deep space',            tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-cyan-400',   swatches: ['bg-violet-950', 'bg-cyan-400',   'bg-violet-900'],  supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-gold',     nameTh: 'Luxury Gold',     nameEn: 'Luxury Gold',     descriptionTh: 'พื้นดำ ทองบริสุทธิ์ Luxury',            descriptionEn: 'Pure black with pure gold luxury',             tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-yellow-400', swatches: ['bg-stone-950',   'bg-yellow-400', 'bg-stone-900'],  supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:dark-mono',     nameTh: 'Mono Minimal',    nameEn: 'Mono Minimal',    descriptionTh: 'ขาวดำ Minimal หมดจด',                   descriptionEn: 'Pure monochrome minimalism',                   tagTh: 'มืดทรงพลัง', tagEn: 'Dark', accentClass: 'bg-white',      swatches: ['bg-neutral-950', 'bg-white',       'bg-neutral-800'], supports: ALL_DOCUMENT_TYPES },
  // ── Anime / Otaku ──────────────────────────────────────────────
  { id: 'builtin:anime-ink',     nameTh: 'Anime Black Ink',    nameEn: 'Anime Black Ink',    descriptionTh: 'สไตล์มังงะ ขาวดำ หมึก',                  descriptionEn: 'Manga-style black ink on white',               tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-red-600',    swatches: ['bg-neutral-900', 'bg-red-600',    'bg-white'],       supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-flame',   nameTh: 'Anime Red Flame',    nameEn: 'Anime Red Flame',    descriptionTh: 'เปลวไฟแดง พลังนักสู้',                   descriptionEn: 'Fierce red flame energy',                      tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-red-500',    swatches: ['bg-red-700',     'bg-red-400',    'bg-red-50'],      supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-energy',  nameTh: 'Anime Blue Energy',  nameEn: 'Anime Blue Energy',  descriptionTh: 'พลังน้ำเงิน สายฟ้า',                     descriptionEn: 'Electric blue energy burst',                   tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-blue-500',   swatches: ['bg-blue-700',    'bg-blue-400',   'bg-blue-50'],     supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-shadow',  nameTh: 'Anime Purple Shadow', nameEn: 'Anime Purple Shadow', descriptionTh: 'เงาม่วง พลังมืด',                       descriptionEn: 'Dark purple shadow power',                     tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-purple-500', swatches: ['bg-purple-700',  'bg-purple-400', 'bg-purple-50'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-mecha',   nameTh: 'Anime Mecha Gear',   nameEn: 'Anime Mecha Gear',   descriptionTh: 'หุ่นยนต์กล Mecha สีเทา',                descriptionEn: 'Mecha steel gray robotic',                     tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-slate-500',  swatches: ['bg-slate-800',   'bg-slate-400',  'bg-slate-100'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-chibi',   nameTh: 'Anime Chibi Cute',   nameEn: 'Anime Chibi Cute',   descriptionTh: 'จิบิน่ารัก ชมพู ดาว',                   descriptionEn: 'Chibi-cute pink with sparkles',                tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-pink-500',   swatches: ['bg-pink-500',    'bg-pink-300',   'bg-pink-50'],     supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-idol',    nameTh: 'Anime Idol Stage',   nameEn: 'Anime Idol Stage',   descriptionTh: 'Idol เวที ทอง แสงสว่าง',                 descriptionEn: 'Idol stage gold and spotlight',                tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-yellow-500', swatches: ['bg-yellow-600',  'bg-yellow-300', 'bg-yellow-50'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-fantasy', nameTh: 'Anime Fantasy',      nameEn: 'Anime Fantasy',      descriptionTh: 'แฟนตาซี เขียวมรกต ป่าวิเศษ',            descriptionEn: 'Mystical forest green fantasy',                tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-emerald-600',swatches: ['bg-emerald-700', 'bg-emerald-400','bg-emerald-50'],   supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-tokyo',   nameTh: 'Anime Tokyo Night',  nameEn: 'Anime Tokyo Night',  descriptionTh: 'Tokyo ยามค่ำ Neon แดง',                  descriptionEn: 'Tokyo night neon red cityscape',               tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-red-500',    swatches: ['bg-indigo-950',  'bg-red-500',    'bg-indigo-900'],  supports: ALL_DOCUMENT_TYPES },
  { id: 'builtin:anime-pastel',  nameTh: 'Anime Pastel Otaku', nameEn: 'Anime Pastel Otaku', descriptionTh: 'Otaku พาสเทล ม่วงอ่อน',                  descriptionEn: 'Otaku soft pastel violet',                     tagTh: 'อนิเมะ', tagEn: 'Anime', accentClass: 'bg-violet-400', swatches: ['bg-violet-200',  'bg-violet-400', 'bg-violet-50'],   supports: ALL_DOCUMENT_TYPES },
];

export function supportsDocumentType(template: BuiltinDocumentTemplate, type: InvoiceType) {
  return template.supports.includes(type);
}
